### ISSUE TITLE
Mode Status confusing 

### ISSUE THREAD

**Issue by JonnyFPV** [SaibotFlow/marax-monitor#3]
Hi, 

Thank you for your great work. Works like a charm… using it without reed sensor. 👍

I have an lelit pl62x v2 with latest software. So the modes changed by lelit. 

If I put the xmode switch in 0 position, the machine works in coffee mode. So the heater is not on during brewing. The display showing a little X above the timer. 

In xmode switch 1 the machine is in steam priority mode. Heater is on during brewing. it shows a little c on the display.

can so make it print a c for coffee mode and a s for steam mode? 

And what would be nice if the timer starts in brewing  I would like to have the timer full screen.

Regards
Jan

**Comment by SaibotFlow** [comment]
Hi Jan,

Thanks for your comment and it's nice to hear that other people are having success with my timer :-)

This is the data you get in version 1.06:
**C**1.06,116,124,093,0840,1,0\n

If it starts with C, it is the coffee mode
If it starts with V, it is Vapour -> SteamMode 


As you described, they changed it. For me, the machine runs in coffee mode when the switch is at 1.
But the display shows C or S,depending on the first letter in the data stream. 

Unfortunately, there is no official documentation on how the data changed in each version. 
On the other hand, I can't imagine that they changed the data stream. 

Unfortunately, I can't offer you the option to display the timer in full screen mode. Because there is no way to change the mode. You need a pyhsic switch or something like that to change the mode. For me, for example, it's important to see the temperature while brewing because I want to monitor the temperature and checking if its stay constant.

But you can fork the project and make the adjustments yourself. :-) 
I would suggest that you develop a sketch that shows the data out in raw format. Then I can implement the changes per version. Otherwise you can use your laptop with the arudino ide. Connect the arudino via usb to the laptop and use the serial monitor of the arudino. You have to collect the data and print it your serial monitor like "Serial.println(receivedData)".

I hope I could help you!
Have a nice weekend!

Greetings
Tobi

**Comment by JonnyFPV** [comment]
Hi Tobi, 

thank you for your reply.

The argument for monitoring temperature is good. :) i saw a project that switches the timer to full screen if the pump start. I thought it would be nice. But monitoring temperatures is also great. 

So my coding skills are not very good. I understand a little bit of the code only while reading. 😂

The latest software changed a lot. Old hx mode was deleted and new added. You can test that to see if you have newest version. If your machine is in coffee mode ( heater is off while brewing to have better temperature stability) the led behind the power button blinks 5 times if you turn the machine on. If you are in steam mode (heater is on while brewing to have more steam power) the led is not flashing. Booth modes now use pid. There is a YouTube video from lelit about that. All machines produced late 11/2021 might have that.

I want help you to improve your project. I can collect some data for you if you can help me or provide me a code for simple data collecting. 

I don’t know how to implement that in your code. 🥲

so you can contact me by email if you want. jnowak@coalmail.de 

Awaiting you reply :)

**Comment by DirkDiggler8** [comment]
Thanks @SaibotFlow  for this.. I took you code as base. I wanted a different screen layout for pump timer.

@JonnyFPV You can check this out if you want a new screen for pump timer. 
https://github.com/DirkDiggler8/marax

**Comment by JonnyFPV** [comment]
> Thanks @SaibotFlow for this.. I took you code as base. I wanted a different screen layout for pump timer.
> 
> @JonnyFPV You can check this out if you want a new screen for pump timer. https://github.com/DirkDiggler8/marax

Thank you for your great work too. A little Bug: if the Boiler Temp goes above. 100c, the Text size is to big. The c symbol goes over to the Steam Temp information. But this is not a big problem, because the temp normally is not above 100c. beside that, its looks really good. :-)

https://ibb.co/QF7HszQ
https://ibb.co/x8ckmpb

My machine behaves like that 
https://www.youtube.com/watch?v=PtlAXnModyM

My machine Data output Serial Monitor:
Switch Position 0 - +1.06,124,118,094,0000,0,0 
Switch Position 1 - C1.06,125,118,094,0000,0,0

So I changed the displayed Mode to my behavior for my machine. Thank You :-)

**Comment by SaibotFlow** [comment]
Hi guys!

all clear! You are welcome to take my project as a basis and customize it according to your wishes :-) 

@JonnyFPV
Thanks for the info. I'll note it in the project soon for people to look out for. 
My machine was purchased 4 months ago. And the data string shows the same firmware. 

I will close the issue now then.
Have fun with the marax monitor :-P
